[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
addopts = "--cov=ssmal --cov-report xml"

[tool.black]
line-length = 140
skip-magic-trailing-comma = true

[tool.pyright]
include = ["src/ssmal", "tests"]
